apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: binance-websocket 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: binance-websocket 
  template:
    metadata:
      labels:
        app: binance-websocket 
    spec:
        containers:
        - name: binance-websocket 
          image: us.gcr.io/fomo-204904/binance-websocket:dev
          imagePullPolicy: Always 
          command: [
            "./binance-websocket",
            "--selector=static",
            "--server_address=:8080"
          ]
          envFrom:
          - configMapRef:
              name: fomo-config
          env:
          - name: UPDATED_AT
            value: "Wed Aug 29 11:12:43 MDT 2018" 
          ports:
          - containerPort: 8080
            name: binance-port
